#!/usr/bin/bash
#
#   pacman-to-cache: Download updates to pacman cache.
#
#   based on checkupdates: Safely print a list of pending updates.
#   Copyright (c) 2013 Kyle Keen <keenerd@gmail.com>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

: ${PACMAN_TO_CACHE_DB:="/run/pacman-to-cache-db/"}

trap 'rm -f $PACMAN_TO_CACHE_DB/db.lck' INT TERM EXIT

DBPath="${DBPath:-/var/lib/pacman/}"
eval $(awk -F' *= *' '$1 ~ /DBPath/ { print $1 "=" $2 }' /etc/pacman.conf)
CacheDir="${CacheDir:-/var/cache/pacman/pkg/}"
eval $(awk -F' *= *' '$1 ~ /CacheDir/ { print $1 "=" $2 }' /etc/pacman.conf)

if [[ -s "$DBPath/db.lck" ]]; then
	echo "pacman is locking the database."
	exit 1
fi

if [[ ! -d "$PACMAN_TO_CACHE_DB" ]]; then
	mkdir -p "$PACMAN_TO_CACHE_DB"
	ln -s "${DBPath}/local" "$PACMAN_TO_CACHE_DB"
	cp -a "${DBPath}/sync" "$PACMAN_TO_CACHE_DB"
fi

pacman -Syuw -q --noconfirm --dbpath "$PACMAN_TO_CACHE_DB" --cachedir "$CacheDir" --logfile /dev/null

# vim: set ts=2 sw=2 noet:
